### ISSUE TITLE
Time series plotter: Attribute error when selecting substance in model that contains pumps

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedigrid#233]
How to reproduce:
- Add the simulation results from this dataset to the project: https://nelenschuurmans-my.sharepoint.com/:f:/g/personal/leendert_vanwolfswinkel_nelen-schuurmans_nl/EuvNX92q3vdGibq4RCymN4UBZ4DQBVH8K4dfHtJIKeSz_A?e=Vqb08l
- Open the Time series plotter
- Click on a node
- As variable, select "Breach" (this is a bit confusing, but "Breach" is the name of the substance)
- The error below is raised

At first glance, to me this looks as an inconsistency in threedigrid (Lines and Nodes having a Meta property but Pumps not?), that would better be fixed there rather than in 3Di Results Analysis. But I may be wrong.

```
AttributeError: 'Pumps' object has no attribute 'Meta' 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_graph\graph_view.py", line 582, in parameter_change
    self.graph_plot.set_parameter(self.current_parameter, time_units)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_graph\graph_view.py", line 246, in set_parameter
    item.plots(self.current_parameter["parameters"], time_units=self.current_time_units, absolute=self.absolute)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_graph\graph_model.py", line 122, in plots
    ts_table = self.timeseries_table(
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_graph\graph_model.py", line 152, in timeseries_table
    pump_fields = set(list(ga.pumps.Meta.composite_fields.keys()))
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\threedi_results_analysis\deps\threedigrid\orm\base\models.py", line 194, in __getattribute__
    attr = super().__getattribute__(attr_name)
AttributeError: 'Pumps' object has no attribute 'Meta'
``

**Comment by margrietpalm** [comment]
@leendertvanwolfswinkel @hoanphungt which version of threedigrid is being used here?

**Comment by margrietpalm** [comment]
Tried to reproduce this with master of threedigrid:

```python
from pathlib import Path
from threedigrid.admin.gridresultadmin import GridH5ResultAdmin

basedir = Path()
result_file = basedir.joinpath( "results_3di.nc")
grid_file = basedir.joinpath("gridadmin.h5")
gr = GridH5ResultAdmin(str(grid_file), str(result_file))
print(gr.has_pumpstations)
> True
print(gr.pumps.Meta.composite_fields)
> {'q_pump': ['Mesh1D_q_pump'], '_mesh_id': ['Mesh1DPump_id']}
```

**Comment by daanvaningen** [comment]
`composite_fields` specifies which fields are present in the result file, `composite_fields` has no meaning outside the domain of results. Therefore I think that `GridH5Admin.pumps.Meta.composite_fields` does not make sense. I don't think we can include `Meta.composite_fields` on the normal `Nodes`, `Lines` etc without a results file.

So I think this can be solved by either using a different interface in the result analysis or not relying the Meta field

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns could you please have a look at this issue with the additional insights from @daanvaningen? I would really like this issue to be resolved, it affects very many cases with WQ simulations.
