### ISSUE TITLE
timeseries_filter error

### ISSUE THREAD

**Issue by jpprins1** [nens/threedigrid#82]
<threedigrid.admin.gridresultadmin.GridH5ResultAdmin object at 0x7f85ca038eb8>
In [5]: results.nodes.infiltration_rate_simple
*** AttributeError: 'Nodes' object has no attribute 'timeseries_filter'

**s1 does work:**

In [6]: results.nodes.s1
array([[0.        , 1.2       , 1.2       , 1.2       , 1.2       ],
       [0.        , 1.19001751, 1.19001751, 1.19001751, 1.19001751],
       [0.        , 1.18003708, 1.18003708, 1.18003708, 1.18003708],
       [0.        , 1.17005925, 1.17005925, 1.17005925, 1.17005925],
       [0.        , 1.16008481, 1.16008481, 1.16008481, 1.16008481],
       [0.        , 1.150115  , 1.150115  , 1.150115  , 1.150115  ],
       [0.        , 1.14015188, 1.14015188, 1.14015188, 1.14015188],
       [0.        , 1.13019924, 1.13019924, 1.13019924, 1.13019924],
       [0.        , 1.1202655 , 1.1202655 , 1.1202655 , 1.1202655 ],
       [0.        , 1.11037642, 1.11037642, 1.11037642, 1.11037642]])

**Comment by martijn-siemerink** [comment]
There is another bug:

gr.nodes.subset('2D_OPEN_WATER').timeseries(start_time=0, end_time=3600).ucx

Traceback (most recent call last):
 File "<input>", line 1, in <module>
 File "C:\ProgramData\Anaconda3\envs\default\lib\site-packages\threedigrid\orm\base\models.py", line 254, in __getattribute__
   'get_filtered_field_value')(attr_name)
 File "C:\ProgramData\Anaconda3\envs\default\lib\site-packages\threedigrid\orm\base\models.py", line 191, in get_filtered_field_value
   value = self.get_field_value(field_name, **kwargs)
 File "C:\ProgramData\Anaconda3\envs\default\lib\site-packages\threedigrid\orm\base\models.py", line 150, in get_field_value
   self._datasource, field_name, **kwargs)
 File "C:\ProgramData\Anaconda3\envs\default\lib\site-packages\threedigrid\orm\base\fields.py", line 203, in get_value
   source_data = datasource[self._source_name][timeseries_filter]
 File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
 File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
 File "C:\ProgramData\Anaconda3\envs\default\lib\site-packages\h5py\_hl\dataset.py", line 553, in __getitem__
   selection = sel.select(self.shape, args, dsid=self.id)
 File "C:\ProgramData\Anaconda3\envs\default\lib\site-packages\h5py\_hl\selections.py", line 72, in select
   sel[arg]
 File "C:\ProgramData\Anaconda3\envs\default\lib\site-packages\h5py\_hl\selections.py", line 214, in __getitem__
   raise TypeError("Boolean indexing array has incompatible shape")
TypeError: Boolean indexing array has incompatible shape
